import os


class Config:
    SECRET_KEY = '0917b13a9091915d54b6336f45909539cce452b3661b21f386418a257883b30a'
    SQLALCHEMY_DATABASE_URI = os.environ.get('SQLALCHEMY_DATABASE_URI')
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    ENDPOINT_ROUTE = 'http://kidfin.thinger.appspot.com'
    LOGIN_URL = '/login'
    NORMAL_REGISTER_URL = '/register'
    DASHBOARD_URL = '/dashboard'
    REQUEST_HELP_URL = '/queues/add'
    HELPER_CHECK_IN_URL = '/check_in'
    HELPER_NOT_FOUND_URL = '/queues/not_found'
    HELPER_HELPED_URL = '/queues/modify/helped'
    HELPERS_ONLINE_URL = '/users/helpers'
    HELPER_INFO_URL = '/info/helper'
    REQUESTER_INFO_URL = '/info/requester'
    ALL_HELPERS_URL = '/info/helpers'
    ALL_REQUESTERS_URL = '/info/requesters'
    ENTER_COMPANY_QUEUE_URL = '/queue/enter'
    MASTER_DASH_INFO_URL = '/master/dashboard/info'
    ADD_COMPANY_URL = '/company/add'
    ADD_COMPANY_ADMIN_URL = '/company/add_user'
    GET_COMPANY_DATA_URL = '/company/all'
    ADMIN_DASHBOARD_INFO_URL = '/admin/dashboard/info'
    ALL_CALLING_URL = '/company/all/calling'
    ALL_ACTIVE_COMPANY_URL = '/company/list_active'
    SESSIONS_URL = '/sessions'
    LISTS_URL = '/lists'
    QUEUE_EXIT_URL = '/queue/exit'
    HELPER_CHECK_OUT_URL = '/check_out'
    NO_SHOW_URL = '/no_show'
    DONE_URL = '/done'
    ADD_RECRUITER_URL = '/company/add_recruiter'
    KIDS_DATA_URL = '/kid/all'
    TRANSACTION_DATA_URL = '/transactions/view'
    CURR_BALANCE_URL = '/transactions/curr_balance'
    EDIT_RESTRICTIONS_URL = '/kid/add_restriction'
    ADD_KID_URL = '/kid/add'
